name: CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: [windows-2019]

    steps:
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      
    - uses: actions/checkout@v1
    - name: Build
      run: |
        git submodule update --init --recursive
        dotnet restore
        dotnet build 
        dotnet publish -r netcoreapp3.1 --self-contained true
    - name: Create ZIP
      run: |
        Compress-Archive -Path src/VMAttack/bin/Debug/* -DestinationPath devm.zip
        
    - name: Archive ViewDistanceTweaks
      uses: actions/upload-artifact@v2
      with:
        path: devm.zip
        name: devm.zip
